name: First workflow
on: push

jobs:
  build:
    runs-on: ubnuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Run a sample github action
       run: echo "this workflow works sucessfully"
